#!/usr/bin/env bash

#/ command: fenchenko:igor: "Prints all input variables"
#/ usage: rerun fenchenko:igor [options]
#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
#/ option-variables: 

. "$RERUN_MODULE_DIR/lib/functions.sh" "igor" || { 
  echo >&2 "Failed loading function library." ; exit 1 ; 
}

set -o errexit -o nounset -o pipefail

rerun_options_parse "$@"

# Command implementation
# ----------------------

# - - -
# Put the command implementation here.
# - - -

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
for var in "$@"
do
  if  [[ $var == --* ]] ;
    then
      echo -e -n "${RED}$var${NC} "
  fi
  if  [[ $var != --* ]] ;
    then
      echo -e "${GREEN}$var${NC}"
  fi
done

# Done. Exit with last command exit status.
exit $?

